name: CI/CD Kubernetes Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t nodejs-cicd:v1 .

      - name: Save image to file
        run: docker save nodejs-cicd:v1 -o image.tar

      - name: Copy image to Kubernetes node
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.K8S_HOST }}
          username: ubuntu
          key: ${{ secrets.K8S_KEY }}
          source: "image.tar"
          target: "/home/ubuntu/"

      - name: Load & Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.K8S_HOST }}
          username: ubuntu
          key: ${{ secrets.K8S_KEY }}
          script: |
            docker load -i image.tar
            kubectl apply -f /home/ubuntu/k8s/
